# Generated by Django 4.2.5 on 2023-09-26 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('price_scrapper', '0003_alter_product_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='last_scrape',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
