# Generated by Django 4.2.5 on 2023-09-26 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('price_scrapper', '0004_product_last_scrape'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='las_web_price_update',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
