# Generated by Django 4.2.5 on 2023-09-26 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('price_scrapper', '0005_product_las_web_price_update'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='las_web_price_update',
            new_name='last_web_price_update',
        ),
    ]
