# Generated by Django 4.2.5 on 2023-10-30 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('price_scrapper', '0006_rename_las_web_price_update_product_last_web_price_update'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='price',
            new_name='scrap_price',
        ),
        migrations.AddField(
            model_name='product',
            name='web_price',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
