# Generated by Django 4.2.5 on 2023-11-18 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('price_scrapper', '0007_rename_price_product_scrap_price_product_web_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='AED_price',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
